export PS1="%F{magenta}λ%f "
export CLICOLOR=1
export PAGER=most
alias ls="ls -F"
alias emacs="emacs -nw"
alias vim="/usr/bin/vim -u /Users/tomasramos/.config/vim/.vimrc"
PATH="$HOME/anaconda3/bin:$PATH"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/tomasramos/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/tomasramos/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/tomasramos/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/tomasramos/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
